### ISSUE TITLE
sub.ready is not a function

### ISSUE THREAD

**Issue by shawnmclean** [JcBernack/meteor-reactive-aggregate#19]
I'm recieving an error of:

```
I20161017-14:49:52.502(-5)? Exception from sub survey id Y2arbPuvporwGJoso TypeError: sub.ready is not a function                                                                                                        
I20161017-14:49:52.504(-5)?     at ReactiveAggregate (packages/jcbernack_reactive-aggregate/aggregate.js:50:1)                                                                                                           
I20161017-14:49:52.505(-5)?     at Subscription._handler (server/main.js:20:5)                                                                                                                                           
I20161017-14:49:52.505(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)                                                                                                             
I20161017-14:49:52.506(-5)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)                                                                                                             
I20161017-14:49:52.506(-5)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)                                                                                                             
I20161017-14:49:52.507(-5)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)                                                                                                                           
I20161017-14:49:52.507(-5)?     at packages/ddp-server/livedata_server.js:551:43 
```

I've tried in 2 separate projects, one which is brand new.

The publish looks like this:

```
import { Meteor } from 'meteor/meteor';
import { ReactiveAggregate } from 'meteor/jcbernack:reactive-aggregate';
import { Books } from  '../imports/Books';

Meteor.publish('aggTest', () => {
    const pipeline = [
        {
            $project: {
                _id: 1,
                amount: true,
            }
        }        
    ]
    ReactiveAggregate(this, Books, pipeline)
})
```

Meteor Stats:

```
meteor npm --version
3.10.8
meteor node --version
v4.6.0
```

**Comment by shawnmclean** [comment]
The other project's error is:

```
I20161017-14:55:26.760(-5)? Exception from sub survey id xjhERD8crNGWZRsaa TypeError: sub.added is not a function                                                                                                        
I20161017-14:55:26.761(-5)?     at meteor://�app/packages/jcbernack_reactive-aggregate/aggregate.js:18:1                                                                                                                 
I20161017-14:55:26.762(-5)?     at Array.forEach (native)                                                                                                                                                                
I20161017-14:55:26.762(-5)?     at update (meteor://�app/packages/jcbernack_reactive-aggregate/aggregate.js:16:1)                                                                                                        
I20161017-14:55:26.763(-5)?     at ReactiveAggregate (meteor://�app/packages/jcbernack_reactive-aggregate/aggregate.js:48:1)                                                                                             
I20161017-14:55:26.763(-5)?     at Subscription.Meteor.publish.url [as _handler] (meteor://�app/imports/api/server/publications/surveys.js:47:5)                                                                         
I20161017-14:55:26.764(-5)?     at maybeAuditArgumentChecks (meteor://�app/packages/ddp-server/livedata_server.js:1711:12)                                                                                               
I20161017-14:55:26.764(-5)?     at Subscription._runHandler (meteor://�app/packages/ddp-server/livedata_server.js:1026:17)                                                                                               
I20161017-14:55:26.765(-5)?     at Session._startSubscription (meteor://�app/packages/ddp-server/livedata_server.js:845:9)                                                                                               
I20161017-14:55:26.765(-5)?     at Session.sub (meteor://�app/packages/ddp-server/livedata_server.js:617:12)                                                                                                             
I20161017-14:55:26.767(-5)?     at meteor://�app/packages/ddp-server/livedata_server.js:551:43  
```

I was getting the previous error before about `sub.ready`. Now it's `sub.added` with my just updating from meteor 1.4.1.1 to 1.4.1.2.

**Comment by JcBernack** [comment]
You can't use the ES6 arrow function with `Meteor.publish` because the publication is passed in as the `this` object. If you are not familiar with the difference, see http://es6-features.org/#Lexicalthis
