### ISSUE TITLE
Cannot set property '_ids' of undefined

### ISSUE THREAD

**Issue by Fauphi** [JcBernack/meteor-reactive-aggregate#33]
I get this error message after adding the $match to the pipeline: 

> Exception from sub grouped-custom-pages id fYKiYT3M2CZ8KTSk6 TypeError: Cannot set property '_ids' of undefined
    I20171214-12:31:50.169(1)?   at ReactiveAggregate (packages/jcbernack_reactive-aggregate.js:31:12)

this is my publication:

```
Meteor.publish("grouped-custom-pages", (type) => {
        ReactiveAggregate(this, CustomPages, 
            [
                {
                    $match: {
                        type: type
                    }
                },
                {
                    $group: {
                        _id: "$languageId",
                        createdAt: {$push: "$createdAt"},
                        pages: { $push: {title: "$title", id: "$_id", language: "$language", type: "$type", published: "$published", mainImage: "$mainImage" }}
                    }
                }
            ], 
            { clientCollection: "GroupedCustomPages" }
        );
    });
```

the query works fine in i.e. Robomongo, so whats the problem here?

**Comment by arthurkirkosa** [comment]
What was the solution for this issue?

**Comment by Fauphi** [comment]
I didn't pass the 'type' param in the subscription, so there where no matches.

**Comment by arthurkirkosa** [comment]
What ever I do I keep getting the error

```
// /imports/model/Flights.js
const Flights = new Mongo.Collection('flights');

export default Flights;

```

```
import Flights from '/imports/model/Flights.js';

Meteor.publish('daily-aggregate-flights', ({ date, query }) => {
    const filter = {
        ...filters({ type: 'departure', date, query }),
        'linkback.ref_id': { $exists: true },
    };

    console.log(filter);

    ReactiveAggregate(this, Flights, [
        { $match: filter },
        {
            $lookup: {
                from: 'flights',
                localField: 'linkback.ref_id',
                foreignField: 'ref_id',
                as: 'linked_flight',
            },
        },
        { $unwind: '$linked_flight' },
    ]);
});
```

```
(console log)
I20180228-11:14:47.346(2)? { flight_time:
I20180228-11:14:47.346(2)?    { '$gte': 2018-02-28T00:00:00.000Z,
I20180228-11:14:47.347(2)?      '$lte': 2018-02-28T23:59:59.999Z },
I20180228-11:14:47.347(2)?   type: 'departure',
I20180228-11:14:47.347(2)?   'linkback.ref_id': { '$exists': true } }

I20180228-11:14:47.348(2)? Exception from sub daily-aggregate-flights id h98TuBkL8vazqa995 TypeError: Cannot set property '_ids' of undefined
I20180228-11:14:47.348(2)?     at ReactiveAggregate (packages/jcbernack_reactive-aggregate.js:31:12)
I20180228-11:14:47.348(2)?     at Subscription._handler (server/flights.js:63:5)
I20180228-11:14:47.349(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180228-11:14:47.349(2)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
I20180228-11:14:47.349(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20180228-11:14:47.350(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20180228-11:14:47.350(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20180228-11:14:47.350(2)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20180228-11:14:47.350(2)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by arthurkirkosa** [comment]
`Meteor.publish('daily-aggregate-flights', function ({ date, query }) {` fixed it since I'm using `this`
