### ISSUE TITLE
Reactive aggregate is not defined

### ISSUE THREAD

**Issue by gustawdaniel** [JcBernack/meteor-reactive-aggregate#45]
I installed by:

    meteor add jcbernack:reactive-aggregate

I created publication

```
Meteor.publish('notes', function (param) {

        return ReactiveAggregate(this, Note, [{
            $match: {
                userId: getUser(param)._id
            },
        },{
            $lookup: {
                from: 'illnesses',
                localField: 'illnessId',
                foreignField: '_id',
                as: 'illness'
            }
        },{
            $unwind: {
                path: "$illness",
                preserveNullAndEmptyArrays: true
            }
        }]); 

    });

```

I see error

```
Exception from sub notes id GGhA6bvomWkPLGbef ReferenceError: ReactiveAggregate is not defined
I20180809-14:03:42.435(2)?     at Subscription._handler (imports/api/publications.js:105:9)
I20180809-14:03:42.435(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20180809-14:03:42.435(2)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
I20180809-14:03:42.436(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20180809-14:03:42.436(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20180809-14:03:42.436(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20180809-14:03:42.436(2)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20180809-14:03:42.437(2)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by gustawdaniel** [comment]
Meteor version 1.7

**Comment by pedrolucasoliva** [comment]
Same problem here.

**Comment by tiagopaes** [comment]
You guys need to import the ReactiveAggregate module in your script. 

> import {ReactiveAggregate} from 'meteor/jcbernack:reactive-aggregate';

**Comment by JcBernack** [comment]
This package is from the old days where everything was global. The examples were out of date.
